const roles=[{name:'狼人',file:'wolf'},{name:'猎人',file:'hunter'},{name:'女巫',file:'witch'},{name:'平民',file:'villager'},{name:'预言家',file:'seer'}];
const $=id=>document.getElementById(id);let deck=[],used=new Set(),busy=false,round=0,counts=[1,1,1,1,1],pending=null;
function randomInt(max){const a=new Uint32Array(1),limit=Math.floor(4294967296/max)*max;do{crypto.getRandomValues(a)}while(a[0]>=limit);return a[0]%max}
function reset(){if(busy)return;deck=roles.flatMap((r,i)=>Array.from({length:counts[i]},()=>r));for(let i=deck.length-1;i>0;i--){let j=randomInt(i+1);[deck[i],deck[j]]=[deck[j],deck[i]]}used.clear();round++;render();$('deck').classList.remove('shuffling');void $('deck').offsetWidth;$('deck').classList.add('shuffling');setTimeout(()=>$('deck').classList.remove('shuffling'),550)}
function render(){$('count').textContent=`剩余 ${deck.length-used.size} / ${deck.length} 张`;$('hint').textContent=used.size===deck.length?'本轮身份已全部发出。准备好，就开始新一轮。':used.size?'身份已收起，请下一位选一张牌。':'凭直觉，选一张属于你的身份牌。';$('deck').classList.toggle('many',deck.length>5);$('deck').replaceChildren(...deck.map((r,i)=>{const b=document.createElement('button');b.className='card'+(used.has(i)?' used':'');b.style.setProperty('--angle',[-6,-3,0,3,6][i%5]+'deg');b.style.setProperty('--offset',(2-i%5)*20);b.disabled=used.has(i);b.setAttribute('aria-label',used.has(i)?`第${i+1}张，已抽取`:`抽取第${i+1}张身份牌`);if(used.has(i))b.textContent='已抽取';else{b.innerHTML=`<img src="assets/back.webp" alt="陈婧霏版狼人杀卡背" draggable="false"><span class="number">${i+1}</span>`;b.onclick=()=>draw(i)}return b}))}
function draw(i){if(!Number.isInteger(i)||i<0||i>=deck.length)throw new Error('请选择有效的卡牌位置');if(busy||used.has(i))throw new Error('这张牌不可抽取');busy=true;used.add(i);$('front').src=`assets/${deck[i].file}.webp`;$('front').alt=deck[i].name+'身份牌';$('role').textContent=deck[i].name;$('flip').classList.remove('flipped');$('reveal').showModal();setTimeout(()=>$('flip').classList.add('flipped'),80);return {position:i+1,role:deck[i].name,remaining:deck.length-used.size}}
function hide(){$('reveal').close();busy=false;$('flip').classList.remove('flipped');$('front').removeAttribute('src');$('front').alt='';$('role').textContent='';render();const next=$('deck').querySelector('button:not(:disabled)');(next||$('shuffle')).focus()}
$('close').onclick=hide;$('next').onclick=hide;$('reveal').addEventListener('cancel',e=>{e.preventDefault();hide()});$('shuffle').onclick=()=>{pending=null;if(used.size&&used.size<deck.length)$('confirm').showModal();else reset()};$('cancel').onclick=()=>{pending=null;$('confirm').close()};$('restart').onclick=()=>{$('confirm').close();if(pending){counts=pending;pending=null}reset()};
$('role-inputs').innerHTML=roles.map((r,i)=>`<label>${r.name}<input type="number" min="0" max="30" step="1" value="1" name="role${i}" aria-label="${r.name}数量" required></label>`).join('');
function readCounts(){return [...$('role-inputs').querySelectorAll('input')].map(el=>el.value===''?NaN:Number(el.value))}
$('config').oninput=()=>{const c=readCounts();$('total').textContent=`共 ${c.every(Number.isInteger)?c.reduce((a,b)=>a+b,0):'—'} 位玩家`;$('config-error').textContent=''};
$('config').onsubmit=e=>{e.preventDefault();const c=readCounts(),total=c.reduce((a,b)=>a+b,0);if(c.some(n=>!Number.isInteger(n)||n<0||n>30)||total<1||total>60){$('config-error').textContent='每种角色可设置 0–30 张，总人数需为 1–60 人。';return}if(used.size&&used.size<deck.length){pending=c;$('confirm').showModal()}else{counts=c;reset()}};reset();
roles.forEach(r=>{const im=new Image();im.src=`assets/${r.file}.webp`});
if(document.modelContext?.registerTool){const controller=new AbortController();for(const tool of [{name:'draw_identity_card',description:'抽取指定位置的身份牌，在屏幕上揭晓并从本轮牌组移除。',inputSchema:{type:'object',properties:{position:{type:'integer',minimum:1,maximum:60}},required:['position'],additionalProperties:false},execute:async input=>{if(!input||Object.keys(input).length!==1)throw new Error('需要position参数');const result=draw(input.position-1);await new Promise(r=>setTimeout(r,750));return result}},{name:'hide_identity_card',description:'收起当前身份，交给下一位玩家。',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:input=>{if(input&&Object.keys(input).length)throw new Error('无需参数');if(!busy)throw new Error('当前没有展示身份');hide();return{remaining:deck.length-used.size}}}]){try{Promise.resolve(document.modelContext.registerTool({...tool,annotations:{readOnlyHint:false,untrustedContentHint:false}},{signal:controller.signal})).catch(()=>{})}catch{}}window.addEventListener('pagehide',()=>controller.abort(),{once:true})}
